// This file was auto-generated by ML.NET Model Builder.
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace MachineLearning4Water_Models
{
    public partial class ConsumHabitatgesModel
    {
        /// <summary>
        /// model input class for ConsumHabitatgesModel.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [LoadColumn(1)]
            [ColumnName(@"Persones_habitatge")]
            public float Persones_habitatge { get; set; }

            [LoadColumn(2)]
            [ColumnName(@"Tipus_habitatge")]
            public float Tipus_habitatge { get; set; }

            [LoadColumn(3)]
            [ColumnName(@"Lavabos_habitatge")]
            public float Lavabos_habitatge { get; set; }

            [LoadColumn(4)]
            [ColumnName(@"Rentavaixelles")]
            public float Rentavaixelles { get; set; }

            [LoadColumn(5)]
            [ColumnName(@"Us_banyera")]
            public float Us_banyera { get; set; }

            [LoadColumn(6)]
            [ColumnName(@"Consum_mensual_m3")]
            public float Consum_mensual_m3 { get; set; }

            [LoadColumn(7)]
            [ColumnName(@"Wc_diari")]
            public float Wc_diari { get; set; }

            [LoadColumn(8)]
            [ColumnName(@"Dutxes_diari")]
            public float Dutxes_diari { get; set; }

            [LoadColumn(9)]
            [ColumnName(@"Tipus_caldera")]
            public float Tipus_caldera { get; set; }

            [LoadColumn(12)]
            [ColumnName(@"Antiguitat_caldera")]
            public float Antiguitat_caldera { get; set; }

            [LoadColumn(13)]
            [ColumnName(@"Caldera_antiga")]
            public float Caldera_antiga { get; set; }

            [LoadColumn(14)]
            [ColumnName(@"Distancia_caldera_dutxa")]
            public float Distancia_caldera_dutxa { get; set; }

            [LoadColumn(15)]
            [ColumnName(@"Temps_aigua_calenta")]
            public float Temps_aigua_calenta { get; set; }

            [LoadColumn(17)]
            [ColumnName(@"Tipus_descarrega")]
            public float Tipus_descarrega { get; set; }

            [LoadColumn(20)]
            [ColumnName(@"Cisterna_capacitat")]
            public float Cisterna_capacitat { get; set; }

            [LoadColumn(22)]
            [ColumnName(@"Seguiment_factura")]
            public float Seguiment_factura { get; set; }

            [LoadColumn(24)]
            [ColumnName(@"Estalvies_aigua")]
            public float Estalvies_aigua { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for ConsumHabitatgesModel.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"Persones_habitatge")]
            public float Persones_habitatge { get; set; }

            [ColumnName(@"Tipus_habitatge")]
            public float Tipus_habitatge { get; set; }

            [ColumnName(@"Lavabos_habitatge")]
            public float Lavabos_habitatge { get; set; }

            [ColumnName(@"Rentavaixelles")]
            public float Rentavaixelles { get; set; }

            [ColumnName(@"Us_banyera")]
            public float Us_banyera { get; set; }

            [ColumnName(@"Consum_mensual_m3")]
            public float Consum_mensual_m3 { get; set; }

            [ColumnName(@"Wc_diari")]
            public float Wc_diari { get; set; }

            [ColumnName(@"Dutxes_diari")]
            public float Dutxes_diari { get; set; }

            [ColumnName(@"Tipus_caldera")]
            public float Tipus_caldera { get; set; }

            [ColumnName(@"Antiguitat_caldera")]
            public float Antiguitat_caldera { get; set; }

            [ColumnName(@"Caldera_antiga")]
            public float Caldera_antiga { get; set; }

            [ColumnName(@"Distancia_caldera_dutxa")]
            public float Distancia_caldera_dutxa { get; set; }

            [ColumnName(@"Temps_aigua_calenta")]
            public float Temps_aigua_calenta { get; set; }

            [ColumnName(@"Tipus_descarrega")]
            public float Tipus_descarrega { get; set; }

            [ColumnName(@"Cisterna_capacitat")]
            public float Cisterna_capacitat { get; set; }

            [ColumnName(@"Seguiment_factura")]
            public float Seguiment_factura { get; set; }

            [ColumnName(@"Estalvies_aigua")]
            public float Estalvies_aigua { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"Score")]
            public float Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("ConsumHabitatgesModel.mlnet");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);


        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }
    }
}
