// This file was auto-generated by ML.NET Model Builder.
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace MachineLearning4Water_Models
{
    public partial class GalindoModel
    {
        /// <summary>
        /// model input class for GalindoModel.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [LoadColumn(1)]
            [ColumnName(@"Temperature")]
            public float Temperature { get; set; }

            [LoadColumn(2)]
            [ColumnName(@"H2O")]
            public float H2O { get; set; }

            [LoadColumn(3)]
            [ColumnName(@"IN_1S_F")]
            public float IN_1S_F { get; set; }

            [LoadColumn(4)]
            [ColumnName(@"IN_1S_I")]
            public float IN_1S_I { get; set; }

            [LoadColumn(5)]
            [ColumnName(@"IN_S_COD")]
            public float IN_S_COD { get; set; }

            [LoadColumn(6)]
            [ColumnName(@"IN_S_NH")]
            public float IN_S_NH { get; set; }

            [LoadColumn(7)]
            [ColumnName(@"IN_X_H")]
            public float IN_X_H { get; set; }

            [LoadColumn(8)]
            [ColumnName(@"IN_X_I")]
            public float IN_X_I { get; set; }

            [LoadColumn(9)]
            [ColumnName(@"IN_X_S")]
            public float IN_X_S { get; set; }

            [LoadColumn(10)]
            [ColumnName(@"IN_X_COD")]
            public float IN_X_COD { get; set; }

            [LoadColumn(11)]
            [ColumnName(@"IN_X_TSS")]
            public float IN_X_TSS { get; set; }

            [LoadColumn(20)]
            [ColumnName(@"OUT_X_TSS")]
            public float OUT_X_TSS { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for GalindoModel.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"Temperature")]
            public float Temperature { get; set; }

            [ColumnName(@"H2O")]
            public float H2O { get; set; }

            [ColumnName(@"IN_1S_F")]
            public float IN_1S_F { get; set; }

            [ColumnName(@"IN_1S_I")]
            public float IN_1S_I { get; set; }

            [ColumnName(@"IN_S_COD")]
            public float IN_S_COD { get; set; }

            [ColumnName(@"IN_S_NH")]
            public float IN_S_NH { get; set; }

            [ColumnName(@"IN_X_H")]
            public float IN_X_H { get; set; }

            [ColumnName(@"IN_X_I")]
            public float IN_X_I { get; set; }

            [ColumnName(@"IN_X_S")]
            public float IN_X_S { get; set; }

            [ColumnName(@"IN_X_COD")]
            public float IN_X_COD { get; set; }

            [ColumnName(@"IN_X_TSS")]
            public float IN_X_TSS { get; set; }

            [ColumnName(@"OUT_X_TSS")]
            public float OUT_X_TSS { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"Score")]
            public float Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("GalindoModel.mlnet");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);


        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }
    }
}
